### ISSUE TITLE
Distribute as JS and HTML?

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#1]
Just wondering, since this is a pure JS lib, would it make sense to distribute as both a `.min.js` and a `.html` file, like `simpla-paths`?

**Comment by bedeoverend** [comment]
Yup I'm pro this 👍

**Comment by madeleineostoja** [comment]
Only thing is I don't know if script tags dedupe... do they?

**Comment by madeleineostoja** [comment]
After all that's the whole point of a shared behavior (unlike simpla-paths)

**Comment by bedeoverend** [comment]
Nah, they don't dedupe. It's much of a muchness - we probably won't use it, so maybe just leave it off until either we have a need, or someone else uses this and asks for it? Its just if someone else wants to be able to take this and bake it into whatever they're doing, then they'd want a UMD module to consume I'd say.

**Comment by madeleineostoja** [comment]
Hmm I'd say let's just leave it as HTML for now, can always re look when native ES6 modules roll around and can properly dedupe JS
