### ISSUE TITLE
State history isn't working

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-richtext-behavior#11]
Doesn't look like history plugin is working - or at least the keymappings for undo / redo aren't working, might not necessarily mean the entire history plugin is failing.

**Comment by madeleineostoja** [comment]
Why do we need history plugin? Contenteditable has native undo/redo support? Or does ProseMirror clobber that?

**Comment by bedeoverend** [comment]
Yeah ProseMirror clobbers it. When it says it re-implements contenteditable, they _really_ mean it, everything is stripped back.

_Edit: Pretty sure it clobbers it for good reason, though I haven't looked through the plugin itself. But it means you can do things like serialize it into JSON and re-hydrate history later on, not that we'll be using that_

**Comment by bedeoverend** [comment]
🤦

**Comment by madeleineostoja** [comment]
Lel
