### ISSUE TITLE
Img align center shouldn't set top and bottom margin

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#12]
Since the alignment styles are written inline and the dev would have to use `!important` to overwrite them, they shouldn't set anything they don't absolutely have to.

Therefore, center aligned images should be:

```css
display: block;
margin-left: auto;
margin-right: auto;
```

**Comment by bedeoverend** [comment]
Is it worth telling the element to do this? i.e. just have the `data-alignment` property and then tell `simpla-article` to style images through slots, that would then reduce the specificity? Bit shit for consumers of richtext to have to set this up, but might be less evil of the two?

**Comment by madeleineostoja** [comment]
Amounts to the same thing - 'consumers of richtext' === us. Not across slotted specificity, but for the end user it'd behave virtually the same anyway.

**Comment by bedeoverend** [comment]
From a specificity POV slotted will be lower - did a quick test and `:host ::slotted(a) { border: solid; }` and some stylesheet in the doc with `a { border: none; }` don't get a border: doc stylesheet wins.
