### ISSUE TITLE
Tapping placeholder does not focus cursor on Safari

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#21]
It's impossible to focus on an editor by clicking on the placeholder in Safari, you can only focus on it by clicking _after_ the placeholder, which is both incredibly unintuitive, and for inline simpla-text impossible.

This effects production `simpla-text`, so is urgent and breaking

Screencap repro:

![cannot focus in safari](https://cloud.githubusercontent.com/assets/6374876/26547427/51aa012a-446f-11e7-9e67-64663f694ca0.gif)

**Comment by madeleineostoja** [comment]
Have not tested whether #16 fixes yet

**Comment by bedeoverend** [comment]
See attached commit. Initially thought it was just forcing the selection that would fix it, but nope. Not really sure why but adding a zero width space to before the actual placeholder meant Safari would focus on it. Logically, no idea why, but figured it was something to do with Safari needing an extra piece of DOM to sit the cursor next to.

**Comment by madeleineostoja** [comment]
That seems to be the case for most things that happen to work on Safari - "no idea why this works, but hey, it's Safari". Coolio.
