### ISSUE TITLE
Make selected img nodes selection transparent

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-richtext-behavior#7]
Right now when you select an img node, it'll be overlaid with the normal blue selection box. This selection should be transparent - ProseMirror normally achieves this by getting you to include their stylesheet and [setting `::selection` to be transparent](https://github.com/ProseMirror/prosemirror-view/blob/master/style/prosemirror.css#L26) when selecting nodes.

Also because images are inserted inside `p` and in Shadow DOM v1 you can only style top level child nodes, you can't style images inside the element using richtext behavior e.g. `simpla-article`. 

The most likely workaround will be a similar behavior to what we're doing with the placeholder plugin, where we inject `style` tags into the element using ProseMirror widgets. It's pretty messy, but it'll work, and ProseMirror can handle ensuring the style tag doesn't get clobbered.

**Comment by bedeoverend** [comment]
Alternative to this would be changing how to handle images. Right now they're inserted into a `p` tag, but this causes problems anyway as a `p` tag's schema allows one or more inline elements inside it, which means it can insert an `img` inside it _and_ then have text either side of it. 

What might be better is having `embed('image')` actually insert a `<figure><img/></figure>` block, then ProseMirror can select the `figure` element which we can style as it's a top-level child (or rather, ask the element e.g. `simpla-article` to style it). This would also fix `p` being able to contain images and text.

**Comment by madeleineostoja** [comment]
You mean the blue outline when you focus on something?

```css
outline: none;
```

Re: embeding, is there a reason we can't just insert a plain `<img>` on its own? Why does it have to be wrapped?

**Comment by madeleineostoja** [comment]
FWIW can't repro this, whatever it is. 

By selecting an image do you mean dragging over it with highlight? That's normal behavior. Way to focus an image should be to tap it.

**Comment by bedeoverend** [comment]
Yeah dragging over it with highlight. If you tap it, it won't focus on the img because it's not an input. ProseMirror handles it by actually 'highlighting' it when you tap on it i.e. simulating dragging over it. Then the 'img' is selected. It's actually a really nice solution because the img is actually highlighted. And it's a general behavior for any future embed. 

Doesn't have to wrapped I don't think - I'm just using the default ProseMirror schema which means images get inserted inline inside `p`. But I can have a play with a custom schema and see how they play sitting by themselves.

**Comment by bedeoverend** [comment]
> embeding, is there a reason we can't just insert a plain <img> on its own?

Just realised they should be able to be embedded inside a `p` so when aligned left / right the text will wrap. Unless there's another way to do that?

**Comment by bedeoverend** [comment]
Fixed in 3f73355b9d15397baae9a0c7e4a78bf526f2df45, makes image top-level nodes so can be styled through `::slotted`

**Comment by madeleineostoja** [comment]
FWIW tapping to focus worked for me /shrug

**Comment by bedeoverend** [comment]
Sorry yeah so ProseMirror automatically handles taps / clicks and selects it, but the node itself isn't 'focused' as such, just highlighted / selected by ProseMirror. At least, I'm pretty sure that's how it worked
