### ISSUE TITLE
Inserting image doesn't preserve selection

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#9]
Use-case: embed image on first (and only) line of article

Result: Can't focus on anything but the image, because no text nodes are preserved

**Comment by bedeoverend** [comment]
After discussion IRL:

Easiest option here is to always insert a new line of text after embedding an object

**Comment by madeleineostoja** [comment]
Not sure what changed, but this isn't much of an issue any more. It's pretty easy/intuitive to select text around image nodes now. Maybe because images are a top-level node? No idea.

Probably still good to auto-insert an extra line, so it's easier to keep writing after embedding an image (especially for floated images), but lower priority than before.

**Comment by madeleineostoja** [comment]
Ohh it's because I added padding to the article demos, so it's easy to select node immediately left/right of image. Welp, can't rely on that. So this is still breaking.
